export const keySectors = [
  {
    id: 1,
    title: "Logistics & Supply Chain",
    bg: "/home/keysectors/supply.png",
    link: "/logistics",
    // colSpan: 1,
    // rowSpan: 2,
    // gradient: true,
  },
  {
    id: 2,
    title: "Packaging",
    bg: "/home/keysectors/package.png",
    link: "/packaging",
  },
  {
    id: 3,
    title: "Automotive & Auto Components",
    bg: "/home/keysectors/auto.png",
    link: "/automotive",
  },
  {
    id: 4,
    title: "E-Commerce",
    bg: "/home/keysectors/ecommerce.png",
    link: "/ecommerce",
  },
  {
    id: 5,
    title: "Renewable Energy",
    bg: "/home/keysectors/energy.png",
    link: "/renewable-energy",
  },
  {
    id: 6,
    title: "Engineering & Aerospace",
    bg: "/home/keysectors/aero.png",
    link: "/aerospace",
  },
  {
    id: 7,
    title: "FMCG & Retail",
    bg: "/home/keysectors/FMCG.png",
    link: "/fmcg",
  },
  {
    id: 8,
    title: "Chemicals",
    bg: "/home/keysectors/chemical.png",
    link: "/chemical",
    // colSpan: 1,
    // rowSpan: 2,
    // gradient: true,
  },
];
